vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    mappings:
        trick_image:
            uri_prefix: /media/tricks/images
            upload_destination: '%kernel.project_dir%/public/media/tricks/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer